# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-28 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('nom_cuenta', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('codigo_cuenta', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('cuenta_padre', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='general.Cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debe', models.FloatField()),
                ('haber', models.FloatField()),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('autorizo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DocLibro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=20)),
                ('debe', models.FloatField()),
                ('haber', models.FloatField()),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Cuenta')),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Diario')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoCuenta',
            fields=[
                ('nom_grupo', models.CharField(max_length=50, unique=True)),
                ('codigo_gcuenta', models.CharField(max_length=2, primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LibroMayor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debe', models.FloatField()),
                ('haber', models.FloatField()),
                ('fecha', models.DateField()),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoContable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('usr_aperturo', models.CharField(max_length=20)),
                ('usr_cerro', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCuenta',
            fields=[
                ('nom_tipo', models.CharField(max_length=50)),
                ('codigo_tcuenta', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('disminuye_en', models.CharField(max_length=10)),
                ('aumenta_en', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='grupocuenta',
            name='tipo_cuenta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='general.TipoCuenta'),
        ),
        migrations.AddField(
            model_name='diario',
            name='libro_mayor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.LibroMayor'),
        ),
        migrations.AddField(
            model_name='diario',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.PeriodoContable'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.GrupoCuenta'),
        ),
    ]
